[package]
name = "traq-markdown-wasm"
version.workspace = true
description = "WebAssembly interface for the shared Markdown parser."
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib"]

[features]
contracts = ["markdown-parser/contracts","dep:ts-rs", "dep:schemars", "markdown-commonmark-contracts/contracts", "markdown-generic-contracts/contracts", "markdown-trap-contracts/contracts"]

[[bin]]
name = "export-node-contracts"
required-features = ["contracts"]

[dependencies]
markdown-parser = { path = "../core/parser" }
markdown-traq = { path = "../trap/traq" }
markdown-codec = { path = "../core/codec" }
markdown-ast = { path = "../core/ast" }
markdown-definitions = { path = "../core/definitions" }
markdown-commonmark-contracts = { path = "../commonmark/contracts" }
markdown-generic-contracts = { path = "../commonmark/extensions/contracts" }
markdown-trap-contracts = { path = "../trap/contracts" }
ts-rs = { version = "12", optional = true, features = ["serde-json-impl"] }
schemars = { version = "1.2.2", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
