name: Rust and TypeScript CI
on: [push, pull_request]
permissions:
  contents: read
jobs:
  check:
    defaults:
      run:
        working-directory: core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: core
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - uses: actions/setup-go@v6
        with:
          go-version-file: core/go/go.mod
          cache-dependency-path: core/go/go.sum
      - run: go -C go test ./...
      - run: cargo test --locked --workspace --all-features
      - run: cargo fmt --all --check
      - run: cargo clippy --locked --workspace --all-targets --all-features -- -D warnings

      - run: npm ci
      - run: npm run build
      - run: npm run typecheck
      - run: npm test
